use odalybr_register;
CREATE TABLE IF NOT EXISTS `member` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` text,
  `phone` varchar(20) DEFAULT '',
  `phone2` varchar(20) DEFAULT '',
  `dob` date DEFAULT '1900-01-01',
  `email` varchar(100) DEFAULT '',
  `amount` varchar(10) DEFAULT '0',
  `receiptid` varchar(20) DEFAULT '0',
  `team` int(11) DEFAULT '0',
  `team2` int(11) DEFAULT '0',
  `team3` int(11) DEFAULT '0',
  `position` int(11) DEFAULT '1',
  `position2` int(11) DEFAULT '1',
  `position3` int(11) DEFAULT '1',
  `lid` int(11) DEFAULT '0',
  `favteam` varchar(30) DEFAULT '',
  `favplayer` varchar(30) DEFAULT '',
  `sappears` int(11) DEFAULT '0',
  `sassists` int(11) DEFAULT '0',
  `sgoals` int(11) DEFAULT '0',
  `photo` varchar(100) DEFAULT 'assets/img/Players/default.png',
  `achievements` text,
  `status` varchar(20) DEFAULT '',
  `academyinfo` text,
  PRIMARY KEY (`id`),
  KEY `team` (`team`)
);